GOOGLE_CLIENT_EMAIL=op://Private/Mnemora/GOOGLE_CLIENT_EMAIL
GOOGLE_PRIVATE_KEY=op://Private/Mnemora/GOOGLE_PRIVATE_KEY
GOOGLE_PROJECT_ID=op://Private/Mnemora/GOOGLE_PROJECT_ID
GOOGLE_SPREADSHEET_ID=op://Private/Mnemora/GOOGLE_SPREADSHEET_ID
WHATSAPP_GROUP_NAME=op://Private/Mnemora/WHATSAPP_GROUP_NAME
