AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch Alarms for Mnemora Birthday Bot Monitoring

Parameters:
  FunctionName:
    Type: String
    Description: Name of the Lambda function
    Default: MnemoraBirthdayBot
  
  DailySummaryFunctionName:
    Type: String
    Description: Name of the daily summary Lambda function
    Default: mnemora-daily-summary-prod
  
  Environment:
    Type: String
    Description: Environment name (dev/prod)
    Default: prod
  
  SnsTopicArn:
    Type: String
    Description: ARN of SNS topic for alerts
    Default: ''
  
  LogGroupName:
    Type: String
    Description: CloudWatch Log Group name
    Default: /aws/lambda/MnemoraBirthdayBot

Resources:
  # SNS Topic for Alerts (if not provided)
  AlertTopic:
    Type: AWS::SNS::Topic
    Condition: CreateSnsTopic
    Properties:
      TopicName: mnemora-birthday-bot-alerts
      DisplayName: Mnemora Birthday Bot Alerts

  # Email Subscription (optional - uncomment and set email)
  # AlertEmailSubscription:
  #   Type: AWS::SNS::Subscription
  #   Properties:
  #     TopicArn: !Ref AlertTopic
  #     Protocol: email
  #     Endpoint: your-email@example.com

  # Alarm: Monthly digest not sent
  MonthlyDigestNotSentAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${FunctionName}-MonthlyDigestNotSent'
      AlarmDescription: Alert when monthly digest is not sent on the 1st of the month
      MetricName: monitoring.monthly_digest_sent
      Namespace: Mnemora/BirthdayBot
      Statistic: Sum
      Period: 86400
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: LessThanThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref FunctionName
      AlarmActions:
        - !If
          - UseProvidedSnsTopic
          - !Ref SnsTopicArn
          - !Ref AlertTopic

  # Alarm: High error rate
  HighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${FunctionName}-HighErrorRate'
      AlarmDescription: Alert when error rate exceeds 10% of executions
      MetricName: execution.failed
      Namespace: Mnemora/BirthdayBot
      Statistic: Sum
      Period: 3600
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref FunctionName
      AlarmActions:
        - !If
          - UseProvidedSnsTopic
          - !Ref SnsTopicArn
          - !Ref AlertTopic

  # Alarm: WhatsApp authentication failures
  WhatsAppAuthFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${FunctionName}-WhatsAppAuthFailure'
      AlarmDescription: Alert when WhatsApp authentication fails
      MetricName: whatsapp.auth.required
      Namespace: Mnemora/BirthdayBot
      Statistic: Sum
      Period: 3600
      EvaluationPeriods: 1
      Threshold: 3
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref FunctionName
      AlarmActions:
        - !If
          - UseProvidedSnsTopic
          - !Ref SnsTopicArn
          - !Ref AlertTopic

  # Alarm: WhatsApp message send failures
  WhatsAppMessageFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${FunctionName}-WhatsAppMessageFailure'
      AlarmDescription: Alert when WhatsApp message send failures exceed threshold
      MetricName: whatsapp.messages.failed
      Namespace: Mnemora/BirthdayBot
      Statistic: Sum
      Period: 3600
      EvaluationPeriods: 1
      Threshold: 3
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref FunctionName
      AlarmActions:
        - !If
          - UseProvidedSnsTopic
          - !Ref SnsTopicArn
          - !Ref AlertTopic

  # Alarm: Lambda initialization errors (Runtime.Unknown) - Main Function
  LambdaInitErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${FunctionName}-InitError'
      AlarmDescription: Alert when Lambda fails during initialization (Runtime.Unknown) - catches module load errors, missing env vars, etc.
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Sub 'mnemora-birthday-bot-${Environment}'
      AlarmActions:
        - !If
          - UseProvidedSnsTopic
          - !Ref SnsTopicArn
          - !Ref AlertTopic

  # Alarm: Lambda initialization errors (Runtime.Unknown) - Daily Summary Function
  DailySummaryInitErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${DailySummaryFunctionName}-InitError'
      AlarmDescription: Alert when daily summary Lambda fails during initialization (Runtime.Unknown) - catches module load errors, missing env vars, etc.
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref DailySummaryFunctionName
      AlarmActions:
        - !If
          - UseProvidedSnsTopic
          - !Ref SnsTopicArn
          - !Ref AlertTopic

Conditions:
  CreateSnsTopic: !Equals [!Ref SnsTopicArn, '']
  UseProvidedSnsTopic: !Not [!Equals [!Ref SnsTopicArn, '']]

Outputs:
  AlertTopicArn:
    Description: ARN of the SNS topic for alerts
    Value: !If
      - UseProvidedSnsTopic
      - !Ref SnsTopicArn
      - !Ref AlertTopic
    Export:
      Name: !Sub '${AWS::StackName}-AlertTopicArn'

  MonthlyDigestAlarm:
    Description: Alarm for monthly digest monitoring
    Value: !Ref MonthlyDigestNotSentAlarm

  LambdaInitErrorAlarm:
    Description: Alarm for Lambda initialization errors (main function)
    Value: !Ref LambdaInitErrorAlarm

  DailySummaryInitErrorAlarm:
    Description: Alarm for Lambda initialization errors (daily summary function)
    Value: !Ref DailySummaryInitErrorAlarm

