AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mnemora Birthday Bot - AWS Lambda Deployment

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

  GoogleClientEmail:
    Type: String
    Description: Google Service Account Email
    NoEcho: false

  GooglePrivateKey:
    Type: String
    Description: Google Service Account Private Key (base64 encoded)
    NoEcho: true

  GoogleProjectId:
    Type: String
    Description: Google Cloud Project ID
    NoEcho: false

  GoogleSpreadsheetId:
    Type: String
    Description: Google Spreadsheet ID
    NoEcho: false

  WhatsAppGroupName:
    Type: String
    Description: WhatsApp group name for birthday messages
    NoEcho: false

  WhatsAppHealthCheckGroupName:
    Type: String
    Default: ''
    Description: WhatsApp group name for health check messages (optional)
    NoEcho: false

Globals:
  Function:
    Timeout: 900
    MemorySize: 512
    Runtime: nodejs24.x
    Environment:
      Variables:
        NODE_ENV: production
        LOG_LEVEL: info

Conditions:
  HasHealthCheckGroupName: !Not [!Equals [!Ref WhatsAppHealthCheckGroupName, '']]

Resources:
  SessionStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'mnemora-whatsapp-sessions-${Environment}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 7
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
          - Id: DeleteOldMessageLogs
            Status: Enabled
            Prefix: app-data/messages/
            ExpirationInDays: 90
          - Id: DeleteOldExecutionRecords
            Status: Enabled
            Prefix: app-data/executions/
            ExpirationInDays: 90

  BirthdayBotLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/mnemora-birthday-bot-${Environment}'
      RetentionInDays: 30

  BirthdayBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'mnemora-birthday-bot-${Environment}'
      CodeUri: ../dist/
      Handler: lambda/handler.handler
      Runtime: nodejs24.x
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          GOOGLE_CLIENT_EMAIL: !Ref GoogleClientEmail
          GOOGLE_PRIVATE_KEY: !Ref GooglePrivateKey
          GOOGLE_PROJECT_ID: !Ref GoogleProjectId
          GOOGLE_SPREADSHEET_ID: !Ref GoogleSpreadsheetId
          WHATSAPP_GROUP_NAME: !Ref WhatsAppGroupName
          WHATSAPP_HEALTH_CHECK_GROUP_NAME: !If [HasHealthCheckGroupName, !Ref WhatsAppHealthCheckGroupName, '']
          TIMEZONE: 'America/Los_Angeles'
          AWS_S3_BUCKET: !Ref SessionStorageBucket
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:ListBucket
              Resource:
                - !Sub 'arn:aws:s3:::${SessionStorageBucket}/*'
                - !Sub 'arn:aws:s3:::${SessionStorageBucket}'
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            # Runs at 17:00 UTC (~10 AM PDT / ~9 AM PST)
            Schedule: cron(0 17 * * ? *)
            Description: Daily birthday check at 10 AM Pacific time (17:00 UTC, ~10 AM PDT most of year)
            Enabled: true
            Input: '{}'

Outputs:
  BirthdayBotFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt BirthdayBotFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'

  SessionStorageBucketName:
    Description: Name of the S3 bucket for session storage
    Value: !Ref SessionStorageBucket
    Export:
      Name: !Sub '${AWS::StackName}-SessionBucket'

  LogGroupName:
    Description: CloudWatch Log Group name
    Value: !Ref BirthdayBotLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroup'
