AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mnemora Birthday Bot - AWS Lambda Deployment

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name
  
  GoogleCalendarId:
    Type: String
    Description: Google Calendar ID
    NoEcho: false
  
  GoogleClientEmail:
    Type: String
    Description: Google Service Account Email
    NoEcho: false
  
  GooglePrivateKey:
    Type: String
    Description: Google Service Account Private Key (base64 encoded)
    NoEcho: true
  
  GoogleProjectId:
    Type: String
    Description: Google Cloud Project ID
    NoEcho: false
  
  GoogleSpreadsheetId:
    Type: String
    Default: ''
    Description: Google Spreadsheet ID (optional)
    NoEcho: false
  
  WhatsAppGroupId:
    Type: String
    Description: WhatsApp Group Name or ID
    NoEcho: false
  
  AlertEmail:
    Type: String
    Description: Email address for receiving alerts
    NoEcho: false
  
  AlertPhone:
    Type: String
    Default: ''
    Description: Phone number for SMS alerts (optional, e.g., +1234567890)
    NoEcho: false

Globals:
  Function:
    Timeout: 900
    MemorySize: 512
    Runtime: nodejs24.x
    Environment:
      Variables:
        NODE_ENV: production
        LOG_LEVEL: info
        METRICS_NAMESPACE: !Sub 'Mnemora/BirthdayBot/${Environment}'
        ENABLE_CLOUDWATCH_METRICS: 'true'
        AWS_XRAY_ENABLED: 'true'

Conditions:
  HasSpreadsheetId: !Not [!Equals [!Ref GoogleSpreadsheetId, '']]
  HasPhoneNumber: !Not [!Equals [!Ref AlertPhone, '']]

Resources:
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'mnemora-alerts-${Environment}'
      DisplayName: Mnemora Birthday Bot Alerts

  AlertEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlertTopic
      Protocol: email
      Endpoint: !Ref AlertEmail

  AlertSMSSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasPhoneNumber
    Properties:
      TopicArn: !Ref AlertTopic
      Protocol: sms
      Endpoint: !Ref AlertPhone

  SessionStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'mnemora-whatsapp-sessions-${Environment}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 7
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
          - Id: DeleteOldMessageLogs
            Status: Enabled
            Prefix: app-data/messages/
            ExpirationInDays: 90
          - Id: DeleteOldExecutionRecords
            Status: Enabled
            Prefix: app-data/executions/
            ExpirationInDays: 90

  BirthdayBotLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/mnemora-birthday-bot-${Environment}'
      RetentionInDays: 30

  BirthdayBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'mnemora-birthday-bot-${Environment}'
      CodeUri: ../dist/
      Handler: lambda/handler.handler
      Runtime: nodejs24.x
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          GOOGLE_CALENDAR_ID: !Ref GoogleCalendarId
          GOOGLE_CLIENT_EMAIL: !Ref GoogleClientEmail
          GOOGLE_PRIVATE_KEY: !Ref GooglePrivateKey
          GOOGLE_PROJECT_ID: !Ref GoogleProjectId
          GOOGLE_SPREADSHEET_ID: !If [HasSpreadsheetId, !Ref GoogleSpreadsheetId, '']
          WHATSAPP_GROUP_ID: !Ref WhatsAppGroupId
          TIMEZONE: 'America/Los_Angeles'
          AWS_S3_BUCKET: !Ref SessionStorageBucket
          AWS_CLOUDWATCH_LOG_GROUP: !Sub '/aws/lambda/mnemora-birthday-bot-${Environment}'
          AWS_XRAY_ENABLED: 'true'
          SNS_TOPIC_ARN: !Ref AlertTopic
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:ListBucket
              Resource:
                - !Sub 'arn:aws:s3:::${SessionStorageBucket}/*'
                - !Sub 'arn:aws:s3:::${SessionStorageBucket}'
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
        - Statement:
            - Effect: Allow
              Action:
                - cloudwatch:PutMetricData
              Resource: '*'
              Condition:
                StringEquals:
                  'cloudwatch:namespace': !Sub 'Mnemora/BirthdayBot/${Environment}'
        - Statement:
            - Effect: Allow
              Action:
                - xray:PutTraceSegments
                - xray:PutTelemetryRecords
                - xray:GetSamplingRules
                - xray:GetSamplingTargets
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref AlertTopic
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            # Runs at 17:00 UTC (~10 AM PDT / ~9 AM PST)
            Schedule: cron(0 17 * * ? *)
            Description: Daily birthday check at 10 AM Pacific time (17:00 UTC, ~10 AM PDT most of year)
            Enabled: true
            Input: '{}'
      Tracing: Active

  DailySummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'mnemora-daily-summary-${Environment}'
      CodeUri: ../dist/
      Handler: lambda/daily-summary-handler.handler
      Runtime: nodejs24.x
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          NODE_ENV: production
          LOG_LEVEL: info
          AWS_S3_BUCKET: !Ref SessionStorageBucket
          SNS_TOPIC_ARN: !Ref AlertTopic
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - !Sub 'arn:aws:s3:::${SessionStorageBucket}/*'
                - !Sub 'arn:aws:s3:::${SessionStorageBucket}'
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref AlertTopic
      Events:
        DailySummarySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 22 * * ? *)
            Description: Daily alert summary at 10 PM
            Enabled: true
            Input: '{}'

Outputs:
  BirthdayBotFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt BirthdayBotFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'

  SessionStorageBucketName:
    Description: Name of the S3 bucket for session storage
    Value: !Ref SessionStorageBucket
    Export:
      Name: !Sub '${AWS::StackName}-SessionBucket'

  LogGroupName:
    Description: CloudWatch Log Group name
    Value: !Ref BirthdayBotLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroup'

  AlertTopicArn:
    Description: ARN of the SNS topic for alerts
    Value: !Ref AlertTopic
    Export:
      Name: !Sub '${AWS::StackName}-AlertTopic'

